/*****
 *
 *
 * @ Embedded YouTube Player
 * @    v1.0 2025.07.20
 *
 *
 */
let YPlayer=null,timeOut=null,duration=3600,videoId=location.hash.slice(1)??null;const origin="https://cdncorner.sbs";window.addEventListener("hashchange",function(){videoId=location.hash.substring(1)??null,videoId&&YPlayer&&YPlayer.loadVideoById(videoId)});function onStateChange(b){switch(b.data){case YT.PlayerState.PLAYING:{window.parent.postMessage({type:"videoStatus",player:"queue",videoId,duration},"*");break}case YT.PlayerState.ENDED:{window.parent.postMessage({type:"videoEnded",videoId},"*");break}}}function onPlayerReady(){YPlayer.playVideo(),duration=YPlayer.getDuration(),window.parent.postMessage({type:"videoStatus",player:"ready",videoId,duration},"*")}function onYouTubeIframeAPIReady(){videoId&&(YPlayer=new YT.Player("player",{videoId:videoId,events:{onReady:onPlayerReady,onStateChange:onStateChange},origin:location.origin,playerVars:{autoplay:1,controls:1,enablejsapi:1,modestbranding:1,fs:0,rel:0},height:"113",width:"200"}))}window.addEventListener("message",a=>{const b=a.data;if(YPlayer)switch(b.action){case"setVolume":{YPlayer&&YPlayer.setVolume(b.value);break}case"setRate":{YPlayer&&YPlayer.setPlaybackRate(b.value);break}case"getDuration":{window.parent.postMessage({type:"videoStatus",player:"queue",videoId,duration},"*");break}case"stopSegment":{YPlayer&&YPlayer.stopVideo(),timeOut&&clearTimeout(timeOut);break}case"playSegment":{const a=b.segment;if(a.to>a.from&&YPlayer){const b=a.to-a.from,c=1e3*b,d=YPlayer.getPlayerState(),e=()=>{YPlayer.playVideo()},f=()=>{a.repeat?(YPlayer.seekTo(a.from,!0),0<b&&(timeOut&&clearTimeout(timeOut),timeOut=setTimeout(()=>f(),c))):(YPlayer.stopVideo(),timeOut&&clearTimeout(timeOut))},g=()=>{timeOut&&clearTimeout(timeOut),YPlayer.seekTo(a.from,!0),0<b&&(timeOut&&clearTimeout(timeOut),timeOut=setTimeout(()=>f(),c))};d===YT.PlayerState.CUED||d===YT.PlayerState.PAUSED?(e(),setTimeout(g,1e3)):d===YT.PlayerState.PLAYING||d===YT.PlayerState.BUFFERING?g():void 0}break}}});
